services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_contato_seguro
    restart: unless-stopped
    user: "1000:984"
    working_dir: /var/www
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - contato_seguro_net
    ports:
      - '3333:3333'
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_contato_seguro_worker
    restart: unless-stopped
    user: "1000:984"
    working_dir: /var/www
    command: npm run worker:ticket-classification
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      - contato_seguro_net
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules

  db:
    image: postgres:16-alpine
    container_name: test_contato_seguro_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: contato_seguro
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d contato_seguro']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - contato_seguro_net
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: test_contato_seguro_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - contato_seguro_net
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

networks:
  contato_seguro_net:
    driver: bridge

volumes:
  node_modules:
  postgres_data:
  redis_data:
